# -*- coding: utf-8 -*-
"""pdftoword.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nFbzh0Vk-wP0tLR6ujlQEfhGzIQZKKvd
"""

# 📦 Step 1: Install required libraries
!pip install pytesseract pdf2image python-docx Pillow --quiet
!apt install tesseract-ocr poppler-utils -y

from PIL import Image
from pdf2image import convert_from_path
from docx import Document
import pytesseract
import os

# 📌 Step 3: Define helper functions

def image_to_text(image):
    """Extract text from a PIL image using Tesseract OCR."""
    return pytesseract.image_to_string(image)

def pdf_to_images(pdf_path):
    """Convert PDF to list of images."""
    return convert_from_path(pdf_path)

def clean_text(text):
    """Remove non-printable/control characters from text."""
    return ''.join(c for c in text if c.isprintable())

def save_to_docx(text_list, output_file):
    """Save list of cleaned text blocks to a Word document."""
    doc = Document()
    for text in text_list:
        cleaned_text = clean_text(text)
        doc.add_paragraph(cleaned_text)
    doc.save(output_file)

def convert_to_docx(file_path, output_file="output.docx"):
    """Main function: Convert PDF/image to Word document."""
    texts = []

    if file_path.lower().endswith('.pdf'):
        images = pdf_to_images(file_path)
        for i, img in enumerate(images):
            text = image_to_text(img)
            texts.append(f"--- Page {i+1} ---\n{text}")
    else:
        image = Image.open(file_path)
        text = image_to_text(image)
        texts.append(text)

    save_to_docx(texts, output_file)
    print(f"\n✅ Word file saved as: {output_file}")

# 📤 Step 4: Upload your PDF or image
from google.colab import files
uploaded = files.upload()

# 📎 Step 5: Convert and download
input_file = list(uploaded.keys())[0]
output_file = os.path.splitext(input_file)[0] + ".docx"

convert_to_docx(input_file, output_file)

# 📥 Step 6: Download the Word file
files.download(output_file)
